In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
    'I am good boy',
    'I am good developer',
    'understand the meaning of words',
    'your videos are good',]


In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am good boy',
 'I am good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
voc_size=10000

In [7]:
### one hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr


[[5127, 9130, 8597, 9728],
 [5127, 9130, 8597, 9475],
 [5127, 4704, 8597, 9605],
 [1586, 7756, 1909, 5772],
 [1586, 7756, 1909, 7366],
 [5662, 5127, 9302, 8597, 8391],
 [5496, 3963, 661, 1909]]

In [9]:
## word embeddings recommendation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential  
from tensorflow.keras.utils import pad_sequences

In [10]:
import numpy as np  

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5127 9130 8597 9728]
 [   0    0    0    0 5127 9130 8597 9475]
 [   0    0    0    0 5127 4704 8597 9605]
 [   0    0    0    0 1586 7756 1909 5772]
 [   0    0    0    0 1586 7756 1909 7366]
 [   0    0    0 5662 5127 9302 8597 8391]
 [   0    0    0    0 5496 3963  661 1909]]


In [12]:
##feauture representation
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 379ms/step


array([[[ 2.1447029e-02, -1.8242478e-02, -3.5321724e-02, -3.9523639e-02,
         -5.0873868e-03, -3.3442758e-02,  2.0168487e-02, -1.7023433e-02,
         -2.7057637e-02,  4.4731010e-02],
        [ 2.1447029e-02, -1.8242478e-02, -3.5321724e-02, -3.9523639e-02,
         -5.0873868e-03, -3.3442758e-02,  2.0168487e-02, -1.7023433e-02,
         -2.7057637e-02,  4.4731010e-02],
        [ 2.1447029e-02, -1.8242478e-02, -3.5321724e-02, -3.9523639e-02,
         -5.0873868e-03, -3.3442758e-02,  2.0168487e-02, -1.7023433e-02,
         -2.7057637e-02,  4.4731010e-02],
        [ 2.1447029e-02, -1.8242478e-02, -3.5321724e-02, -3.9523639e-02,
         -5.0873868e-03, -3.3442758e-02,  2.0168487e-02, -1.7023433e-02,
         -2.7057637e-02,  4.4731010e-02],
        [ 1.5729669e-02,  7.1092844e-03, -4.3457747e-04, -4.8426904e-02,
         -1.5948638e-03,  4.1388180e-02,  4.6848390e-02,  2.2859965e-02,
         -3.6525119e-02, -4.2204786e-02],
        [ 3.2371286e-02,  1.6193915e-02, -2.4110138e-02, -1.